import { createClient } from '@supabase/supabase-js';

// ------------------------------------------------------------------
// [USER INSTRUCTION]
// Replace the values below with your own Supabase project details.
// You can find these in your Supabase Dashboard -> Settings -> API.
// ------------------------------------------------------------------

const SUPABASE_URL = 'https://drefhlxceslpievzltod.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_tYFi8blJqVdXay3-ggOxHg_kjQGr_oX';

// ------------------------------------------------------------------

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

/**
 * SQL Schema required for this app:
 * 
 * create table public.prayers (
 *   id bigint generated by default as identity primary key,
 *   created_at timestamp with time zone default timezone('utc'::text, now()) not null,
 *   name text not null,
 *   phone text not null,
 *   content text not null,
 *   is_public boolean default true,
 *   prayed_count integer default 0
 * );
 * 
 * -- Run this if you already created the table:
 * -- alter table public.prayers add column prayed_count integer default 0;
 */